sudo: false
language: node_js
node_js:
  - "4"

before_install:
  - "wget https://raw.github.com/arunoda/travis-ci-meteor-packages/master/start_test.js"
  - "wget https://raw.github.com/arunoda/travis-ci-meteor-packages/master/phantom_runner.js"
  - "curl https://install.meteor.com/ | sh"
  - export PATH=$PATH:$HOME/.meteor

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
